[package]
name = "delux_proto"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
prost = "0.12"
tonic = { version = "0.10" }

[build-dependencies]
tonic-build = { version = "0.10", features = ["prost"] }
